name: "preprocessor"
backend: "python"

input [
  {
    name: "x0"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]
input [
  {
    name: "x1"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]
input [
  {
    name: "x2"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]
input [
  {
    name: "x3"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]
input [
  {
    name: "v2000"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]
output [
  {
    name: "INPUT0"
    data_type: TYPE_FP32
    dims: [ 1, 5 ]
  }
]
instance_group [{ kind: KIND_CPU }]
